export const family = {
  // English Fonts
  Poppins_ThinItalic: 'Poppins-ThinItalic',
  Poppins_Thin: 'Poppins-Thin',
  Poppins_SemiBoldItalic: 'Poppins-SemiBoldItalic',
  Poppins_SemiBold: 'Poppins-SemiBold',
  Poppins_Regular: 'Poppins-Regular',
  Poppins_MediumItalic: 'Poppins-MediumItalic',
  Poppins_Medium: 'Poppins-Medium',
  Poppins_LightItalic: 'Poppins-LightItalic',
  Poppins_Light: 'Poppins-Light',
  Poppins_Italic: 'Poppins-Italic',
  Poppins_ExtraLightItalic: 'Poppins-ExtraLightItalic',
  Poppins_ExtraLight: 'Poppins-ExtraLight',
  Poppins_ExtraBoldItalic: 'Poppins-ExtraBoldItalic',
  Poppins_ExtraBold: 'Poppins-ExtraBold',
  Poppins_BoldItalic: 'Poppins-BoldItalic',
  Poppins_Bold: 'Poppins-Bold',
  Poppins_BlackItalic: 'Poppins-BlackItalic',
  Poppins_Black: 'Poppins-Black',

  Amita_Bold: 'Amita-Bold',
  Amita_Regular: 'Amita-Regular',

  BeVietnamPro_Black: 'BeVietnamPro-Black',
  BeVietnamPro_BlackItalic: 'BeVietnamPro-BlackItalic',
  BeVietnamPro_Bold: 'BeVietnamPro-Bold',
  BeVietnamPro_BoldItalic: 'BeVietnamPro-BoldItalic',
  BeVietnamPro_ExtraBold: 'BeVietnamPro-ExtraBold',
  BeVietnamPro_ExtraBoldItalic: 'BeVietnamPro-ExtraBoldItalic',
  BeVietnamPro_ExtraLight: 'BeVietnamPro-ExtraLight',
  BeVietnamPro_ExtraLightItalic: 'BeVietnamPro-ExtraLightItalic',
  BeVietnamPro_Italic: 'BeVietnamPro-Italic',
  BeVietnamPro_Light: 'BeVietnamPro-Light',
  BeVietnamPro_LightItalic: 'BeVietnamPro-LightItalic',
  BeVietnamPro_Medium: 'BeVietnamPro-Medium',
  BeVietnamPro_MediumItalic: 'BeVietnamPro-MediumItalic',
  BeVietnamPro_Regular: 'BeVietnamPro-Regular',
  BeVietnamPro_SemiBold: 'BeVietnamPro-SemiBold',
  BeVietnamPro_SemiBoldItalic: 'BeVietnamPro-SemiBoldItalic',
  BeVietnamPro_Thin: 'BeVietnamPro-Thin',
  BeVietnamPro_ThinItalic: 'BeVietnamPro-ThinItalic',
};
